### ISSUE TITLE
”点击查看“点了没反应

### ISSUE THREAD

**Issue by yizhimengxin2233** [samyycX/VocaloidInfo#2]
如题

**Comment by samyycX** [comment]
经过我的测试仍然能正常显示，能否提供一下您触发bug的详细操作和控制台记录？（按F12点击上方的console）

**Comment by yizhimengxin2233** [comment]
> 经过我的测试仍然能正常显示，能否提供一下您触发bug的详细操作和控制台记录？（按F12点击上方的console）

![image](https://user-images.githubusercontent.com/58097884/235411019-acf383a7-a4a5-4b75-b304-85bec6a4d685.png)
操作就是点开一首曲子(我试的是[https://music.163.com/song?id=22677429](https://music.163.com/song?id=22677429))，等待下方提示之后点"点击查看"，然后就没有反应了

**Comment by samyycX** [comment]
> > 经过我的测试仍然能正常显示，能否提供一下您触发bug的详细操作和控制台记录？（按F12点击上方的console）
> 
> ![image](https://user-images.githubusercontent.com/58097884/235411019-acf383a7-a4a5-4b75-b304-85bec6a4d685.png) 操作就是点开一首曲子(我试的是https://music.163.com/song?id=22677429)，等待下方提示之后点"点击查看"，然后就没有反应了

更新之后也一样吗？有没有安装其他插件？再检查一下能否访问https://vocadb.net/ 这个网站

**Comment by samyycX** [comment]
@yizhimengxin2233 问题解决了么

**Comment by yizhimengxin2233** [comment]
> @yizhimengxin2233 问题解决了么

已解决，感谢回答
(忘记关issues了不好意思)
