### ISSUE TITLE
新成就显示问题

### ISSUE THREAD

**Issue by Boxkun** [samyycX/VocaloidInfo#3]
关于哔哩哔哩的成就 图标缩放问题
![Snipaste_2023-04-29_18-23-39](https://user-images.githubusercontent.com/50022810/235297900-ed092648-c698-4660-9339-07b5415e93bc.png)
复现：
每次必现

多次切换歌曲后成就有几率不显示
![Snipaste_2023-04-29_18-56-27](https://user-images.githubusercontent.com/50022810/235299039-d9426d35-269f-4107-b3ed-537851abd1ee.png)
![Snipaste_2023-04-29_18-57-19](https://user-images.githubusercontent.com/50022810/235299065-c92705dd-e90d-4ccd-b103-f8245a0375a4.png)

复现：
1. 在歌单中双击播放一首歌曲，此时可正常显示成就
2. 两秒钟后 双击切换至另一首
3. 两秒钟后 双击切换至任何（原本可显示成就的）歌曲 此时成就不显示 
4. 等待一段时间后切换至其它歌曲 成就不显示

其它复现方式：
1. 在歌单中双击播放一首歌曲
2. 展开歌曲详情页，此时可正常显示成就
3. 两秒钟后 关闭歌曲详情页
4. 两秒钟后 展开歌曲详情页 成就不显示

可稳定复现

另：如果在详情页中通过底栏 / 键盘媒体控制快速切换歌曲，成就仍可显示

Win10 22H2 19045.2846
分辨率 1920x1080 自定义DPI缩放 108%
网易云 2.10.9 BetterNCM 1.2.0 RefinedNowPlaying 2.19.4

**Comment by samyycX** [comment]
抱歉不小心手滑把issue关了..感谢反馈和pr，问题应该已经修复了，如果还有问题可以继续在这个issue下回复

**Comment by Boxkun** [comment]
刚还想pr来着（
感谢修复
