### ISSUE TITLE
转译模板函数

### ISSUE THREAD

**Issue by std-microblock** [samyycX/VocaloidInfo#5]
https://github.com/samyycX/VocaloidInfo/blob/bb45a764d7c96677ea8de04f1617f23d30e6a441/utils.js#L33-L38

我注意到你写了一个 createNode util 函数，用于直接以 HTML 创建 DOM，并且直接以模板字符串的形式调用了从网络中获取到的数据：

https://github.com/samyycX/VocaloidInfo/blob/bb45a764d7c96677ea8de04f1617f23d30e6a441/component.js#L3-L10

这是非常不安全的，会导致 XSS 攻击，配合 BetterNCM 强大的 API 完全可以实现远程高权限执行，任意代码注入，属于高危漏洞

推荐的解决方法是对注入的字符串进行 HTML 文本转译，类似如下： 

```javascript
const xss = (str)=>dom('div', { innerText:str }).innerHTML;

createNode(`
<div>
${xss(data.text)}
</div>
`);

// 你也可以使用别名以简化书写

const t = xss;

createNode(`
<div>
${t(data.text)}
</div>
`);
```

当然，在允许的情况下，我更推荐使用 `react` `vue` `svelte` 等前端开发框架，他们可以在保证开发效率的同时避免这类安全漏洞。（我个人只推荐 vue 的组合式 API ，选项式实在是太奇怪了……）

希望作者能尽快修复，以避免插件由于安全原因从插件商店中被删除。

**Comment by samyycX** [comment]
非常抱歉，是我写的时候疏忽了，已经在尽力修复这个漏洞了，但是我遇到了一些问题：
使用您给的方法进行转义防止XSS似乎是无效的？
假设输入为:
```javascript
var img = `https://vocadb.net/Content/youtube.png" onmouseover="javascript:alert(0)" \\`;
```
转义:
```javascript
const xss = (str)=>dom('div', { innerText:str }).innerHTML;

var safeImg = xss(img);
```
再拼接:
```javascript
function htmlToNode(html) { 
    return dom('div', {innerHTML:html}).firstElementChild;
}

htmlToNode(`<img src="${safeImg}" width="16px" height="16px"/> `);
```
得到的输出如下:
```javascript
<img src="https://vocadb.net/Content/youtube.png" onmouseover="javascript:alert(0)" \" width="16px" height="16px">
```
经过我的测试，虽然接口不太可能会返回恶意数据，但是此攻击确实有效
想问一下是我哪里写错了吗？
@MicroCBer

**Comment by std-microblock** [comment]
> 非常抱歉，是我写的时候疏忽了，已经在尽力修复这个漏洞了，但是我遇到了一些问题： 使用您给的方法进行转义防止XSS似乎是无效的？ 假设输入为:
> 
> ```js
> var img = `https://vocadb.net/Content/youtube.png" onmouseover="javascript:alert(0)" \\`;
> ```
> 
> 转义:
> 
> ```js
> const xss = (str)=>dom('div', { innerText:str }).innerHTML;
> 
> var safeImg = xss(img);
> ```
> 
> 再拼接:
> 
> ```js
> function htmlToNode(html) { 
>     return dom('div', {innerHTML:html}).firstElementChild;
> }
> 
> htmlToNode(`<img src="${safeImg}" width="16px" height="16px"/> `);
> ```
> 
> 得到的输出如下:
> 
> ```js
> <img src="https://vocadb.net/Content/youtube.png" onmouseover="javascript:alert(0)" \" width="16px" height="16px">
> ```
> 
> 经过我的测试，虽然接口不太可能会返回恶意数据，但是此攻击确实有效 想问一下是我哪里写错了吗？ @MicroCBer

我给的这个示例转义函数并不会处理 " 和 ‘，如果要在属性中安全使用需要这么写：

```javascript
const xss = (str) => {
  const map = {
    '<': '&lt;',
    '>': '&gt;',
    '&': '&amp;',
    '\"': '&quot;',
    '\'': '&#39;'
  };
  return str.replace(/[<>&"']/g, (m) => map[m]);
}
```

或者直接用 npm 上的 xss 库

**Comment by samyycX** [comment]
非常感谢，解决了
