### ISSUE TITLE
建议：优化歌曲名称识别

### ISSUE THREAD

**Issue by Hacinsl** [samyycX/VocaloidInfo#6]
现在的歌曲识别似乎仅对“歌曲标题就是完整曲名且不包含任何其他内容”的曲子正常起效，对于含有“remix”、“xx Ver.”，“重制”等字样的歌曲不能识别，比如《绝体绝命（Love Elegia Ver.）》
建议在识别曲名时支持自动去除“[]”、“【】”、“（）”等括号内的字符，应该很少有正常曲名包含这些特殊字符的
另外还有一些非V曲只是曲名撞了的被识别到了，这个目前也没想到什么解决办法

**Comment by samyycX** [comment]
感谢反馈，会尽快进行这方面的适配
对于撞曲名的问题，我的想法是带上作者名进行查找，但是可能会出现额外的问题，目前还在考虑

**Comment by samyycX** [comment]
@Hacinsl 已经实现相关需求

**Comment by Hacinsl** [comment]
感谢辛勤付出
